# -*- coding: utf-8 -*-
"""Taller1_KevinLl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10kSzzvYuKPEDQBIoeUVMeFxZPB6TNkN8
"""

i=0
a=set()
b=set()
h= int(input("Ingrese el rango de A "))
for i in range (0,h):
  nuevo_A = int(input("Ingrese el valor a agregar en A: "))
  a.add(nuevo_A)
k= int(input("Ingrese el rango de B "))
for i in range (0,k):
  nuevo_B = int(input("Ingrese el valor a agregar en B: "))
  b.add(nuevo_B)


#print(a)
#print(b)

print("---Menu---")
print("1.Union")
print("2.Interseccion")
print("3.Diferencia")
print("4.Diferencia simetrica")
op=int(input("Que operacion quiere realizar: "))
if op == 1:
  print(a|b)
elif op == 2:
  print(a&b)
elif op == 3:
  print(a-b)
  print(b-a)
elif op == 4:
  print(a^b)