# -*- coding: utf-8 -*-
"""Taller2_KevinLl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7TSOmhwSgFRHbP2tTE_-qWfzSub6GGz
"""

i=0
a=set()
b= set()
c={1,4,8,10,12,15,18,20}
d={2,3,5,7,11,13,17,19,23,29,31,37,41,43}

for i in range (5,20):
  nuevo_A = i+1
  a.add(nuevo_A)
print(a)
for i in range (1,25):
  #h=i+1
  if i%2 == 0:
    b.add(i)
print(b)
print(c)
print(d)

def union (a,b):
  return a|b
def intersecion (a,b):
  return a&b
def diferencia (a,b):
  return a-b
def dif_sime (a,b):
  return a^b

op1= intersecion(b,dif_sime(c,d))
print(op1)
op2= union(intersecion(a,c),b)
print(op2)
op3=diferencia(union(b,d),c)
print(op3)
op4=dif_sime(diferencia(a,b),intersecion(a,d))
print(op4)
#print(diferencia(a,b))
#print(intersecion(a,d))